#let standards = [
The main standard used in the UL Solutions reports is UL 2596, Test Method for Thermal and Mechanical Performance of Battery Enclosure Materials. This standard includes two main test methods, the Torch and Grit Test and the Battery Enclosure Thermal Runaway Test. While these two test methods are similar, the Battery Enclosure Thermal Runaway Test is more realistic since it uses actual lithium-ion cells that are forced into thermal runaway. Outside of these two tests included in the UL 2596 standard, the UL Solutions documents also refer to a few international standards: IEC 60695-4, fire hazard testing, and ISO 13943, fire safety vocabulary. All these standards and codes, while they cover different aspects of testing, combine to provide a repeatable, safe, and effective method for testing the performance of battery enclosure materials.]

#let fuel_air = [
The main standard that relates to the torch system is the National Fire Protection Association (NFPA) 54. NFPA 54 offers criteria for installing and operating gas piping and equipment. Since our system will be utilizing methane gas and oxygen flowing through piping to the torch to perform the tests included in UL 2596, following the guidelines of this standard will allow safe installation and operation of the torch.]

#let programming = [
IEC 61508 outlines a methodology for assessing the amount of safety required for a project and then considerations depending on that safety level. Our project falls under the category of general production software, which is a level 3 SIL. This level advises using a structured control flow, limiting pointers, recursion, and interrupts, and avoiding implicit type casting.]

#let analysis = [
The standards outlined above serve as a basis for the design of this project. UL 2596 requires that specific parts and materials are used, such as the type of burner and gas. This standard also requires the use of features like an actuating preheat barrier. NFPA 54 restricts the methods and materials used during the installation of our gas system. As a result, our final gas system design must be based on these criteria. Finally, IEC 61508 provides a general guideline on how to structure the code for our data acquisition software.]
